workflows:
  shofyou-android-build:
    name: Shofyou Android Build
    max_build_duration: 30

    environment:
      groups:
        - keystore_credentials
      java: 17

    scripts:
      - name: Decode Keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > app/shofyou.keystore

      - name: Create signing properties
        script: |
          echo "storeFile=app/shofyou.keystore" > android_signing.properties
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> android_signing.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android_signing.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android_signing.properties

      - name: Build APK
        script: |
          gradle assembleRelease

      - name: Build AAB
        script: |
          gradle bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
