workflows:
  android-workflow:
    name: Shofyou Android Build
    max_build_duration: 60

    environment:
      groups:
        - keystore_credentials

      vars:
        PACKAGE_NAME: "com.shofyou.android"

      java: 17

    scripts:
      - name: Decode Keystore
        script: |
          echo "Generating keystore..."
          keytool -genkey -v \
            -keystore release.keystore \
            -alias $CM_KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            -dname "CN=Shofyou, OU=Mobile, O=Shofyou, L=City, S=State, C=MA"

      - name: Set up signing config
        script: |
          cat > android_signing.properties <<EOF
          storeFile=release.keystore
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$CM_KEY_PASSWORD
          EOF

      - name: Build APK
        script: |
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - release.keystore
