workflows:
  android-shofyou:
    name: Shofyou Professional Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - keystore_credentials
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Prebuild Android
        script: npx expo prebuild --platform android
      - name: Generate Keystore
        script: |
          mkdir -p android/app
          keytool -genkeypair -v -keystore android/app/shofyou.keystore \
            -alias $CM_KEY_ALIAS -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass $CM_KEYSTORE_PASSWORD -keypass $CM_KEY_PASSWORD \
            -dname "CN=Shofyou, OU=Dev, O=Shofyou, L=City, S=State, C=US"
      - name: Build Android App
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
